name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Build Project (without tests)
        run: mvn clean -q compile -DskipTests

      - name: Store Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-artifacts
          path: target/

  integration-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-artifacts
          path: target/

      - name: Run Integration Tests
        run: mvn verify -DskipUnitTests

  database-tests:
    needs: integration-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [ mysql, mssql ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-artifacts
          path: target/

      - name: Run Database Tests with Profile ${{ matrix.profile }}
        run: mvn verify -P${{ matrix.profile }} -DskipUnitTests -DskipIntegrationTests
